[package]
name = "alkahest"
version = "0.4.0"
edition = "2021"
authors = ["cohaereo <cohaereo@protonmail.com>"]

[dependencies]
alkahest-data = { path = "./crates/alkahest-data" }
alkahest-panic-handler = { path = "./crates/alkahest-panic-handler" }
alkahest-pm = { path = "./crates/alkahest-pm" }
tiger-parse = { version = "0.1.5", git = "https://github.com/v4nguard/tiger-parse", features = [
    "check_types",
    "destiny_pkg",
    "check_types_debug",
] }

destiny-havok = { path = "./crates/destiny-havok" }
destiny-pkg = "0.9.9"

anyhow = { version = "1.0.71" }
winit = { version = "0.28" }
binrw = "0.13.3"
itertools = "0.12.1"
ddsfile = "0.5.1"
hex = "0.4.3"
bytemuck = { version = "1.13.1", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

windows = { version = "0.43.0", features = [
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_Graphics_Direct3D_Fxc",
] }
raw-window-handle = "0.5.2"
# u16cstr = "0.4.0"
glam = { version = "0.27", features = ["bytemuck", "mint"] }
fastrand = "2.0.0"

bitflags = "2.3.3"
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.4", features = ["derive"] }
const_format = "0.2.31"
crossbeam = "0.8.2"
egui = { version = "0.24.1", features = ["persistence"] }
egui_commonmark = "0.10.2"
egui-directx11 = { path = "./crates/egui-directx11" }
egui-winit = "0.24.1"
frustum_query = "0.1.2"
genmesh = "0.6.2"
lazy_static = "1.4.0"
mimalloc = { version = "0.1", default-features = false }
num-derive = "0.4.0"
num-traits = "0.2.16"
obj = "0.10.2"
parking_lot = "0.12.1"
png = "0.17.10"
poll-promise = { version = "0.3.0", features = ["tokio"] }
rayon = "1.7.0"
ringbuffer = "0.15"
ron = "0.8.1"
reqwest = { version = "0.11.24", features = ["json"] }
semver = "1.0.21"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.113"
serde_yaml = "0.9.25"
strum = { version = "0.26.1", features = ["derive"] }
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["rt", "macros"] }
tracing-tracy = "0.11.0"
tracy-client = "0.17.0"

# bevy_ecs = "0.11.3"
hecs = "0.10.3"
tinyvec = "1.6.0"
native-dialog = "0.7.0"
paste = "1.0.14"

discord-rpc-client = { version = "0.4.0", optional = true }
fs-err = "2.11.0"
num = "0.4.1"
rustc_version = "0.4.0"
zip-extract = "0.1.3"
build-time = "0.1.3"
rustc-hash = "1.1.0"
once_cell = "1.19.0"
directories = "5.0.1"
game-detector = "0.1.3"
tracing-log = "0.2.0"

[features]
default = ["discord_rpc"]
tracy = []
# Disable sorting the map list
keep_map_order = []
# TODO(cohae): This should be a runtime configuration setting?
discord_rpc = ["dep:discord-rpc-client"]

debug_lock = []
tfx_strict_interpreter = []

[package.metadata.imgui-dx11-renderer]
targets = ["x86_64-pc-windows-gnu"]

[package.metadata.alkahest]
targets = ["x86_64-pc-windows-gnu"]

[profile.dev.package.destiny-pkg]
opt-level = 3

[build-dependencies]
winres = "0.1.12"

[profile.dev]
# opt-level = 3
# cohae: Overflow checks are nice for some, but not for us
overflow-checks = false
